app:
  description: MCP 工具管理平台
  logo_url: ''
  name: MCPS.ONE
  show_title: true
  version: 2.0.0
data_management:
  cleanup_schedule: 0 2 * * *
  cleanup_strategy: auto
  max_backup_files: 10
  max_log_files: 100
  retention_days: 30
database:
  backup_enabled: true
  backup_interval: daily
  backup_retention_days: 30
  echo: false
  url: sqlite:///./data/mcps.db
development:
  debug_toolbar: false
  hot_reload: true
  mock_external_services: false
  profiling: false
features:
  api_docs: true
  auto_update: false
  developer_mode: false
  experimental_features: false
  health_check: true
  verbose_errors: false
  websocket_enabled: true
i18n:
  default_language: zh-CN
  supported_languages:
  - zh-CN
  - en-US
  - ja-JP
  timezone: Asia/Shanghai
logging:
  backup_count: 5
  console_output: true
  file: ./data/logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10MB
mcp:
  api:
    capabilities:
    - list_available_tools
    - call_tool
    - get_tool_capabilities
    - start_tool
    - stop_tool
    - health_check
    - get_metrics
    - http_transport
    - rest_api
    - json_rpc
    enabled: true
    host: 127.0.0.1
    port: 8002
    startup_script: start_mcp_api_server.py
    transport: http
  client_config:
    mcpServers:
      mcps-one-server:
        args:
        - D:/project/MCPS.ONE/backend/start_dynamic_mcp.py
        command: D:/project/MCPS.ONE/backend/.venv/Scripts/python.exe
        env:
          PYTHONIOENCODING: utf-8
          PYTHONPATH: D:/project/MCPS.ONE/backend
  enabled: true
  logs_dir: ./data/logs
  max_processes: 10
  process_timeout: 30
  proxy:
    auto_start: true
    capabilities:
    - list_available_tools
    - call_tool
    - session_isolation
    - concurrent_safety
    - transport_bridging
    enable_metrics: true
    enabled: false
    graceful_shutdown: true
    health_check_interval: 30
    retry_count: 3
    startup_script: start_mcp_proxy_server.py
    tool_startup_timeout: 60
  restart_delay: 5
  server:
    capabilities:
    - list_available_tools
    - call_tool
    - get_tool_capabilities
    - start_tool
    - stop_tool
    - health_check
    - get_metrics
    connection_timeout: 30
    enabled: false
    host: 127.0.0.1
    log_level: INFO
    max_connections: 10
    port: 8001
    show_banner: false
    startup_script: start_mcp_server.py
    stateless_http: false
    transport: http
  service:
    auto_switch: false
    config_check_interval: 5
    graceful_shutdown_timeout: 30
    mode: server
    startup_script: start_dynamic_mcp.py
  tools_dir: ./data/tools
  unified:
    capabilities:
    - list_available_tools
    - call_tool
    - get_tool_capabilities
    - start_tool
    - stop_tool
    - health_check
    - get_metrics
    - session_isolation
    - concurrent_safety
    - mode_switching
    - dynamic_configuration
    enabled: false
    startup_script: start_dynamic_mcp.py
monitoring:
  alert_thresholds:
    cpu_percent: 80
    disk_percent: 90
    error_rate: 5
    memory_percent: 85
  health_check_interval: 30
  metrics_enabled: true
  metrics_interval: 60
notifications:
  email:
    enabled: false
    password: ''
    sender_email: ''
    smtp_host: ''
    smtp_port: 587
    use_ssl: false
    use_tls: true
  webhook:
    enabled: false
    events:
    - tool_error
    - system_error
    - backup_completed
    retry_count: 3
    timeout: 30
    url: ''
performance:
  keepalive_timeout: 65
  max_request_size: 10MB
  request_timeout: 30
  worker_connections: 1000
  worker_processes: 1
security:
  access_token_expire_minutes: 30
  lockout_duration: 300
  max_login_attempts: 5
  password_min_length: 8
  secret_key: your-secret-key-change-in-production
server:
  allowed_hosts:
  - localhost
  - 127.0.0.1
  cors_origins:
  - http://localhost:3000
  - http://localhost:5173
  - http://localhost:5174
  debug: false
  host: 0.0.0.0
  port: 8000
  uploads_dir: ./uploads
