"""Add performance monitoring models

Revision ID: 2b4937531a92
Revises: 06ebad41df36
Create Date: 2025-07-15 02:29:43.931795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4937531a92'
down_revision = '443b0fdea619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###