"""Initial migration

Revision ID: 443b0fdea619
Revises: 
Create Date: 2025-07-14 18:08:52.777244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443b0fdea619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False, comment='备份文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('backup_type', sa.String(length=20), nullable=True, comment='备份类型: manual, auto, scheduled'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='备份状态: running, completed, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_backups_id'), 'database_backups', ['id'], unique=False)
    op.create_table('mcp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False, comment='工具ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=True, comment='工具名称'),
    sa.Column('direction', sa.String(length=10), nullable=True, comment='消息方向: in, out'),
    sa.Column('message_type', sa.String(length=50), nullable=True, comment='消息类型'),
    sa.Column('method', sa.String(length=100), nullable=True, comment='方法名'),
    sa.Column('request_data', sa.JSON(), nullable=True, comment='请求数据'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='响应数据'),
    sa.Column('error_data', sa.JSON(), nullable=True, comment='错误数据'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='处理时间（毫秒）'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='时间戳'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_direction_type_time', 'mcp_logs', ['direction', 'message_type', 'timestamp'], unique=False)
    op.create_index('idx_mcp_tool_time', 'mcp_logs', ['tool_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_mcp_logs_direction'), 'mcp_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_mcp_logs_id'), 'mcp_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_logs_message_type'), 'mcp_logs', ['message_type'], unique=False)
    op.create_index(op.f('ix_mcp_logs_timestamp'), 'mcp_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_mcp_logs_tool_id'), 'mcp_logs', ['tool_id'], unique=False)
    op.create_index(op.f('ix_mcp_logs_tool_name'), 'mcp_logs', ['tool_name'], unique=False)
    op.create_table('mcp_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('type', sa.Enum('BUILTIN', 'CUSTOM', 'EXTERNAL', name='tooltype'), nullable=True, comment='工具类型'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='工具分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='工具标签'),
    sa.Column('command', sa.Text(), nullable=False, comment='启动命令'),
    sa.Column('working_directory', sa.String(length=500), nullable=True, comment='工作目录'),
    sa.Column('environment_variables', sa.JSON(), nullable=True, comment='环境变量'),
    sa.Column('connection_type', sa.String(length=20), nullable=True, comment='连接类型: stdio, http, websocket'),
    sa.Column('host', sa.String(length=100), nullable=True, comment='主机地址（HTTP/WebSocket）'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口号（HTTP/WebSocket）'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='路径（HTTP/WebSocket）'),
    sa.Column('auto_start', sa.Boolean(), nullable=True, comment='自动启动'),
    sa.Column('restart_on_failure', sa.Boolean(), nullable=True, comment='失败时重启'),
    sa.Column('max_restart_attempts', sa.Integer(), nullable=True, comment='最大重启次数'),
    sa.Column('timeout', sa.Integer(), nullable=True, comment='超时时间（秒）'),
    sa.Column('status', sa.Enum('STOPPED', 'STARTING', 'RUNNING', 'STOPPING', 'ERROR', 'UNKNOWN', name='toolstatus'), nullable=True, comment='当前状态'),
    sa.Column('process_id', sa.Integer(), nullable=True, comment='进程ID'),
    sa.Column('last_started_at', sa.DateTime(), nullable=True, comment='最后启动时间'),
    sa.Column('last_stopped_at', sa.DateTime(), nullable=True, comment='最后停止时间'),
    sa.Column('restart_count', sa.Integer(), nullable=True, comment='重启次数'),
    sa.Column('version', sa.String(length=20), nullable=True, comment='工具版本'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='作者'),
    sa.Column('homepage', sa.String(length=500), nullable=True, comment='主页'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tools_category'), 'mcp_tools', ['category'], unique=False)
    op.create_index(op.f('ix_mcp_tools_id'), 'mcp_tools', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_tools_name'), 'mcp_tools', ['name'], unique=True)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID'),
    sa.Column('resource_name', sa.String(length=200), nullable=True, comment='资源名称'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='具体动作: create, update, delete, start, stop'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='操作状态: success, failed, pending'),
    sa.Column('description', sa.Text(), nullable=True, comment='操作描述'),
    sa.Column('old_values', sa.JSON(), nullable=True, comment='变更前的值'),
    sa.Column('new_values', sa.JSON(), nullable=True, comment='变更后的值'),
    sa.Column('result', sa.JSON(), nullable=True, comment='操作结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='请求ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='时间戳'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='操作耗时（毫秒）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ops_action_status_time', 'operation_logs', ['action', 'status', 'timestamp'], unique=False)
    op.create_index('idx_ops_operation_time', 'operation_logs', ['operation', 'timestamp'], unique=False)
    op.create_index('idx_ops_resource_time', 'operation_logs', ['resource_type', 'resource_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_operation_logs_action'), 'operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operation_logs_operation'), 'operation_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_operation_logs_request_id'), 'operation_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource_id'), 'operation_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_resource_type'), 'operation_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_timestamp'), 'operation_logs', ['timestamp'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('value_type', sa.String(length=20), nullable=True, comment='值类型: string, int, float, bool, json'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='配置分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否为公开配置'),
    sa.Column('is_readonly', sa.Boolean(), nullable=True, comment='是否只读'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('system_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='指标名称'),
    sa.Column('metric_value', sa.Text(), nullable=True, comment='指标值'),
    sa.Column('metric_type', sa.String(length=20), nullable=True, comment='指标类型: gauge, counter, histogram'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='时间戳'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_info_category'), 'system_info', ['category'], unique=False)
    op.create_index(op.f('ix_system_info_id'), 'system_info', ['id'], unique=False)
    op.create_index(op.f('ix_system_info_metric_name'), 'system_info', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_info_timestamp'), 'system_info', ['timestamp'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False, comment='日志级别'),
    sa.Column('category', sa.Enum('SYSTEM', 'TOOL', 'API', 'MCP', 'AUTH', 'OPERATION', name='logcategory'), nullable=False, comment='日志分类'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志消息'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='日志来源'),
    sa.Column('tool_id', sa.Integer(), nullable=True, comment='关联工具ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=True, comment='工具名称'),
    sa.Column('details', sa.JSON(), nullable=True, comment='详细信息'),
    sa.Column('stack_trace', sa.Text(), nullable=True, comment='堆栈跟踪'),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='请求ID'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='时间戳'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_category_level_time', 'system_logs', ['category', 'level', 'timestamp'], unique=False)
    op.create_index('idx_logs_source_time', 'system_logs', ['source', 'timestamp'], unique=False)
    op.create_index('idx_logs_tool_time', 'system_logs', ['tool_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_category'), 'system_logs', ['category'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_tool_id'), 'system_logs', ['tool_id'], unique=False)
    op.create_index(op.f('ix_system_logs_tool_name'), 'system_logs', ['tool_name'], unique=False)
    op.create_table('tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='颜色'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_categories_id'), 'tool_categories', ['id'], unique=False)
    op.create_index(op.f('ix_tool_categories_name'), 'tool_categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_categories_name'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_id'), table_name='tool_categories')
    op.drop_table('tool_categories')
    op.drop_index(op.f('ix_system_logs_tool_name'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_tool_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_category'), table_name='system_logs')
    op.drop_index('idx_logs_tool_time', table_name='system_logs')
    op.drop_index('idx_logs_source_time', table_name='system_logs')
    op.drop_index('idx_logs_category_level_time', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_system_info_timestamp'), table_name='system_info')
    op.drop_index(op.f('ix_system_info_metric_name'), table_name='system_info')
    op.drop_index(op.f('ix_system_info_id'), table_name='system_info')
    op.drop_index(op.f('ix_system_info_category'), table_name='system_info')
    op.drop_table('system_info')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_category'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_operation_logs_timestamp'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_resource_type'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_resource_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_request_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_operation'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_action'), table_name='operation_logs')
    op.drop_index('idx_ops_resource_time', table_name='operation_logs')
    op.drop_index('idx_ops_operation_time', table_name='operation_logs')
    op.drop_index('idx_ops_action_status_time', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_mcp_tools_name'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_id'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_category'), table_name='mcp_tools')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_mcp_logs_tool_name'), table_name='mcp_logs')
    op.drop_index(op.f('ix_mcp_logs_tool_id'), table_name='mcp_logs')
    op.drop_index(op.f('ix_mcp_logs_timestamp'), table_name='mcp_logs')
    op.drop_index(op.f('ix_mcp_logs_message_type'), table_name='mcp_logs')
    op.drop_index(op.f('ix_mcp_logs_id'), table_name='mcp_logs')
    op.drop_index(op.f('ix_mcp_logs_direction'), table_name='mcp_logs')
    op.drop_index('idx_mcp_tool_time', table_name='mcp_logs')
    op.drop_index('idx_mcp_direction_type_time', table_name='mcp_logs')
    op.drop_table('mcp_logs')
    op.drop_index(op.f('ix_database_backups_id'), table_name='database_backups')
    op.drop_table('database_backups')
    # ### end Alembic commands ###