"""add users table

Revision ID: 52f6f740362d
Revises: b913facd5fe0
Create Date: 2025-07-18 21:30:24.815366

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '52f6f740362d'
down_revision = 'b913facd5fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话号码'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('theme', sa.String(length=20), nullable=True, comment='主题设置'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言设置'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区设置'),
    sa.Column('email_notifications', sa.Boolean(), nullable=True, comment='邮件通知'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
