"""Add last_error field to mcp_tools table

Revision ID: b9a86d9c925c
Revises: d0225625d590
Create Date: 2025-07-15 17:39:51.164915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a86d9c925c'
down_revision = 'd0225625d590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_tools', sa.Column('last_error', sa.Text(), nullable=True, comment='最后错误信息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_tools', 'last_error')
    # ### end Alembic commands ###
