"""add_last_error_at_to_mcp_tools

Revision ID: d0225625d590
Revises: 2b4937531a92
Create Date: 2025-07-15 16:26:19.157175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0225625d590'
down_revision = '2b4937531a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='会话ID'),
    sa.Column('session_type', sa.Enum('USER', 'SYSTEM', 'API', 'MCP', name='sessiontype'), nullable=True, comment='会话类型'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'TERMINATED', name='sessionstatus'), nullable=True, comment='会话状态'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='会话名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='会话描述'),
    sa.Column('tool_id', sa.Integer(), nullable=True, comment='关联工具ID'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='用户ID'),
    sa.Column('config', sa.Text(), nullable=True, comment='会话配置(JSON)'),
    sa.Column('session_metadata', sa.Text(), nullable=True, comment='会话元数据(JSON)'),
    sa.Column('request_count', sa.Integer(), nullable=True, comment='请求次数'),
    sa.Column('response_count', sa.Integer(), nullable=True, comment='响应次数'),
    sa.Column('error_count', sa.Integer(), nullable=True, comment='错误次数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True, comment='最后活动时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_sessions_id'), 'mcp_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_sessions_session_id'), 'mcp_sessions', ['session_id'], unique=True)
    op.create_table('mcp_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False, comment='任务ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='任务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('task_type', sa.Enum('SINGLE_TOOL', 'MULTI_TOOL', 'WORKFLOW', 'BATCH', 'SCHEDULED', name='tasktype'), nullable=True, comment='任务类型'),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='taskpriority'), nullable=True, comment='任务优先级'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=True, comment='任务状态'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话ID'),
    sa.Column('tool_id', sa.Integer(), nullable=True, comment='主要工具ID'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='用户ID'),
    sa.Column('parent_task_id', sa.Integer(), nullable=True, comment='父任务ID'),
    sa.Column('input_data', sa.Text(), nullable=True, comment='输入数据(JSON)'),
    sa.Column('output_data', sa.Text(), nullable=True, comment='输出数据(JSON)'),
    sa.Column('config', sa.Text(), nullable=True, comment='任务配置(JSON)'),
    sa.Column('task_metadata', sa.Text(), nullable=True, comment='任务元数据(JSON)'),
    sa.Column('progress', sa.Float(), nullable=True, comment='执行进度(0-100)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='错误代码'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='计划执行时间'),
    sa.Column('timeout_at', sa.DateTime(), nullable=True, comment='超时时间'),
    sa.Column('execution_time', sa.Float(), nullable=True, comment='执行时间(秒)'),
    sa.Column('cpu_usage', sa.Float(), nullable=True, comment='CPU使用率'),
    sa.Column('memory_usage', sa.Float(), nullable=True, comment='内存使用量(MB)'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['mcp_tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['mcp_sessions.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tasks_id'), 'mcp_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_tasks_task_id'), 'mcp_tasks', ['task_id'], unique=True)
    op.add_column('mcp_tools', sa.Column('last_error_at', sa.DateTime(), nullable=True, comment='最后错误时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_tools', 'last_error_at')
    op.drop_index(op.f('ix_mcp_tasks_task_id'), table_name='mcp_tasks')
    op.drop_index(op.f('ix_mcp_tasks_id'), table_name='mcp_tasks')
    op.drop_table('mcp_tasks')
    op.drop_index(op.f('ix_mcp_sessions_session_id'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sessions_id'), table_name='mcp_sessions')
    op.drop_table('mcp_sessions')
    # ### end Alembic commands ###
